---
<<<<<<< HEAD
title: "Fixed ops settings titles"
merge_request: 37259
author: Justin Mandell (jmandell)
=======
title: "“Fixed ops settings titles”"
merge_request:37259
author:
>>>>>>> 196073-sentence-case-settings-ops
type: fixed
